<div>
    <h2>
        <?php _e('Yet Another Related Posts Plugin Options','yarpp');?>
        <small>
            <?php echo apply_filters('yarpp_version_html', esc_html(get_option('yarpp_version'))) ?>
        </small>
    </h2>
    <p>
        <strong><em>NEW in YARPP 4.2!</em></strong> &nbsp;Now you can mix and match <strong>YARPP Basic</strong> and
        <strong>YARPP Pro</strong> to get the best of both features! Recommendations from both Basic and Pro can now
        display beneath your articles or in your sidebar (as a <a href="widgets.php">widget</a>) or in both locations.
        Use the combination that works best for you!
    </p>
</div>